services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $rootDir: "%kernel.project_dir%"

    IS\CIValidatorsBundle\Validator\AbstractEntityValidator:
        tags:
            - { name: validator.entity_validator }

    IS\CIValidatorsBundle\Command\SchemaPolicyValidateCommand:
        tags:
            - { name: console.command }

    IS\CIValidatorsBundle\Validator\EntityTableValidator: ~
    IS\CIValidatorsBundle\Validator\EntityPrefixValidator: ~
    IS\CIValidatorsBundle\Validator\EntityColumnsValidator: ~
    IS\CIValidatorsBundle\Validator\EntityIndexesValidator: ~
    IS\CIValidatorsBundle\Validator\EntityUniqueIndexesValidator: ~
    IS\CIValidatorsBundle\Validator\ValidatorCollection: ~
    IS\CIValidatorsBundle\Component\SchemaValidateProcessor: ~
