services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [setContainer, ["@service_container"]]

    IS\CIValidatorsBundle\Validator\AbstractEntityValidator:
        tags:
            - { name: validator.entity_validator }

    IS\CIValidatorsBundle\:
        resource: '../../{Controller,Command,Component/GlobalDbAPI}'

    IS\CIValidatorsBundle\Validator\EntityTableValidator: ~
    IS\CIValidatorsBundle\Validator\EntityPrefixValidator: ~
    IS\CIValidatorsBundle\Validator\EntityColumnsValidator: ~
    IS\CIValidatorsBundle\Validator\EntityIndexesValidator: ~
    IS\CIValidatorsBundle\Validator\EntityUniqueIndexesValidator: ~
    IS\CIValidatorsBundle\Validator\ValidatorCollection: ~
    IS\CIValidatorsBundle\Component\SchemaValidateProcessor: ~
