services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    _instanceof:
        IS\CIValidatorsBundle\Validator\AbstractEntityValidator:
            tags:
                - { name: validator.entity_validator }

    IS\CIValidatorsBundle\Command\SchemaPolicyValidateCommand:
        arguments:
            $rootDir: '%kernel.project_dir%'

    IS\CIValidatorsBundle\Validator\EntityTableValidator: ~
    IS\CIValidatorsBundle\Validator\EntityPrefixValidator: ~
    IS\CIValidatorsBundle\Validator\EntityColumnsValidator: ~
    IS\CIValidatorsBundle\Validator\EntityIndexesValidator: ~
    IS\CIValidatorsBundle\Validator\EntityUniqueIndexesValidator: ~
    IS\CIValidatorsBundle\Validator\ValidatorCollection: ~
    IS\CIValidatorsBundle\Component\SchemaValidateProcessor: ~
